### ISSUE TITLE
수정사항

### ISSUE THREAD

**Issue by probationer070** [probationer070/ProjShop#25]
1.MediaQuery : Login ,Main, ProDuctList, ProductDetail, CartList, OrderDetail, OrderList(X) 적용 대상 - done

2. 갤럭시, 아이폰 분리 - done

3. Searching 무한 스크롤 수정 에러 - done (jiho)

admin OrderDetail 글씨 크기 수정, 글 수정 - done
OrderDetail AddCommas 필요. (doo)
NoticeInform 수정 - done (doo)

**Comment by bburang2** [comment]
3. Searching 무한 스크롤 수정 에러 -> 수정완료

**Comment by ssoeun1** [comment]
admin orderFix 열 간격 맞춤 필요
admin/user notice 제목 정렬맞춤 필요
admin/user member css 조정 필요

media query join css  조정 필요
media query admin login시 화면 깨짐 확인 필요
media query 회원정보 양쪽 여백 조정 필요

**Comment by HanDooSeong** [comment]
1. 회원가입 폼&버튼 오른쪽으로 치우침, 회원 정보*수정도 같음
2. 어드민 상품디테일에서 ::after 지우기.
3. 왼쪽 상단 카테고리 글씨 깨짐.
4. 주문리스트
5. 공지사항 무한스크롤 확인
